= Commerce Cloud B2C Shop Connector Release Notes

November 2020

_Support Category: Select_

Anypoint Connector for Commerce Cloud B2C Shop APIs provides Mule users with a quick and easy way to integrate with Salesforce Commerce Cloud B2C Shop API endpoints.

== 1.0.0
October 2020

This release of Commerce Cloud B2C Shop Connector is compatible with Mule 4 but not Mule 3.

== Compatibility
Commerce Cloud B2C Shop Connector is compatible with these software versions:

[%header%autowidth.spread]
|===
|Software |Version
|Anypoint Studio |7 and later
|Mule runtime engine |4.2.1 and later
|JDK |1.8.x
|===

== Features

Commerce Cloud B2C Shop Connector provides access to Salesforce Commerce Cloud B2C Shop APIs for the below workflows:

* Shopper Customer
* Shopper Baskets
* Shopper Orders
* Shopper Promotions
* Shopper Search
* Shopper Product
* Shopper Gift Certificates

== Fixed in This Release
Not applicable: This is the first released version.

== See Also
* https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Anypoint Connectors Support Policy]
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]
