= Commerce Cloud B2C Shop Connector - Get Started - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../../../assets/images/
Support Category: Select
Commerce Cloud B2C Shop Connector Version Major.Minor.Patch
// Anypoint Connector for Commerce Cloud B2C Shop Connector provides ...

== About Commerce Cloud B2C Shop Connector

Anypoint Connector for Salesforce Commerce Cloud B2C Shop APIs is an operation-based connector, which means that when you add the connector to your flow, you need to configure a specific operation for the connector to perform.

Shop API Connector enables a client to interact with the system as a shop customer or as an agent shopping on behalf of a customer.


== Mule Compatibility

[width="100%", options="header"]
|=======
|Application or Service |Version
|Mule Runtime Engine |4.2.1 and later
|Anypoint Studio | 7 and later
|=======


== Prerequisites

Before creating an app, you must have access to the Commerce Cloud B2C Shop Connector target resource and
Anypoint Platform. You also need to understand how to create a Mule app using
Anypoint Design Center (Design Center) or Anypoint Studio (Studio).

Further, you must be familiar with Mule runtime engine (Mule), Anypoint Connectors, Anypoint Studio Essentials, Mule flows, and Mule Global Elements.

To use Commerce Cloud B2C Shop Connector, you need:

* Anypoint Studio version 7 and later
* Commerce Cloud B2C Shop Connector
* Commerce cloud credentials such as client Id, Client Secret, Scopes to access Shop API which the user needs to get from the Commerce Cloud team.


== Audience
* Starting user:
To create your Mule app,
see xref:shop-api-connector-design-center.adoc[Design Center Configuration]
or xref:shop-api-connector-studio.adoc[Studio Configuration].The
xref:shop-api-connector-examples.adoc[Examples] topic provides one or more use
cases for using the connector.
* Power user:
Visit the xref:shop-api-connector-xml-maven.adoc[XML and Maven
Support] and xref:shop-api-connector-examples.adoc[Examples] topics.

== Common Use Cases For the Connector
See xref:shop-api-connector-examples.adoc[Examples] for a simple use case.


== Next Step

After you meet the prerequisites and experiment with templates and
examples, you are ready to create an app with
xref:shop-api-connector-design-center.adoc[Design Center] or
xref:shop-api-connector-studio.adoc[Anypoint Studio].

== See Also

* https://www.mulesoft.com/exchange/?search= [Anypoint
Exchange]
* https://forums.mulesoft.com[MuleSoft Forum]